-- MNX_FaithPurchase
-- Author: manux
-- DateCreated: 3/9/2024 1:54:58 PM
--------------------------------------------------------------

INSERT OR IGNORE INTO Modifiers 
		(ModifierId,									ModifierType,													Permanent,	SubjectRequirementSetId)
VALUES	-- Faith Purchase
		('MOD_MNX_FAITH_BUY_BUILDINGS_CITYCENTER',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',		1,			'REQSR_MNX_PLAYER_HAS_FOUNDED_RELIGION'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_HOLYSITE',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',		1,			'REQSR_MNX_PLAYER_HAS_FOUNDED_RELIGION'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_HARBOR',			'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',		1,			'REQSR_MNX_PLAYER_HAS_FOUNDED_RELIGION'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_ENCAMPMENT',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',		1,			'REQSR_MNX_PLAYER_HAS_FOUNDED_RELIGION'),
																														
		('MOD_MNX_FAITH_BUY_UNITS_CIVILIAN',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_PLAYER_HAS_FOUNDED_RELIGION'),																													
		('MOD_MNX_FAITH_BUY_UNITS_RECON',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_PLAYER_HAS_FOUNDED_RELIGION'),

		('MOD_MNX_FAITH_BUY_UNITS_SUPPORT',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_MELEE',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_RANGED',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_SIEGE',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_H_CAVAL',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_L_CAVAL',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_R_CAVAL',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_A_CAVAL',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_H_CHARIOT',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
		('MOD_MNX_FAITH_BUY_UNITS_L_CHARIOT',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_ENCAMP_HOLY_TIER3'),
																														
		('MOD_MNX_FAITH_BUY_UNITS_NAV_MELEE',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_HOLY_TIER3_HARBOR_TIER1'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_RANGED',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_HOLY_TIER3_HARBOR_TIER1'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_RAIDER',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_HOLY_TIER3_HARBOR_TIER1'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_CARRIER',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_HOLY_TIER3_HARBOR_TIER1'),
																														
		('MOD_MNX_FAITH_BUY_UNITS_AIRCRAFT',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_TIER3_HOLY_BUILDING'),
		('MOD_MNX_FAITH_BUY_UNITS_HELICOPTER',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			1,			'REQSR_MNX_CITY_HAS_TIER3_HOLY_BUILDING');


INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,						Value)
VALUES	-- Faith Purchase
		('MOD_MNX_FAITH_BUY_BUILDINGS_CITYCENTER',		'DistrictType',				'DISTRICT_CITY_CENTER'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_HOLYSITE',		'DistrictType',				'DISTRICT_HOLY_SITE'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_HARBOR',			'DistrictType',				'DISTRICT_HARBOR'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_ENCAMPMENT',		'DistrictType',				'DISTRICT_ENCAMPMENT'),

		('MOD_MNX_FAITH_BUY_UNITS_CIVILIAN',			'Tag',						'CLASS_LANDCIVILIAN'),

		('MOD_MNX_FAITH_BUY_UNITS_RECON',				'Tag',						'CLASS_RECON'),
		('MOD_MNX_FAITH_BUY_UNITS_SUPPORT',				'Tag',						'CLASS_SUPPORT'),
		('MOD_MNX_FAITH_BUY_UNITS_MELEE',				'Tag',						'CLASS_MELEE'),
		('MOD_MNX_FAITH_BUY_UNITS_RANGED',				'Tag',						'CLASS_RANGED'),
		('MOD_MNX_FAITH_BUY_UNITS_SIEGE',				'Tag',						'CLASS_SIEGE'),
		('MOD_MNX_FAITH_BUY_UNITS_H_CAVAL',				'Tag',						'CLASS_HEAVY_CAVALRY'),
		('MOD_MNX_FAITH_BUY_UNITS_L_CAVAL',				'Tag',						'CLASS_LIGHT_CAVALRY'),
		('MOD_MNX_FAITH_BUY_UNITS_R_CAVAL',				'Tag',						'CLASS_RANGED_CAVALRY'),
		('MOD_MNX_FAITH_BUY_UNITS_A_CAVAL',				'Tag',						'CLASS_ANTI_CAVALRY'),
		('MOD_MNX_FAITH_BUY_UNITS_H_CHARIOT',			'Tag',						'CLASS_HEAVY_CHARIOT'),
		('MOD_MNX_FAITH_BUY_UNITS_L_CHARIOT',			'Tag',						'CLASS_LIGHT_CHARIOT'),

		('MOD_MNX_FAITH_BUY_UNITS_NAV_MELEE',			'Tag',						'CLASS_NAVAL_MELEE'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_RANGED',			'Tag',						'CLASS_NAVAL_RANGED'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_RAIDER',			'Tag',						'CLASS_NAVAL_RAIDER'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_CARRIER',			'Tag',						'CLASS_NAVAL_CARRIER'),
		
		('MOD_MNX_FAITH_BUY_UNITS_AIRCRAFT',			'Tag',						'CLASS_AIRCRAFT'),
		('MOD_MNX_FAITH_BUY_UNITS_HELICOPTER',			'Tag',						'CLASS_HELICOPTER');


INSERT OR IGNORE INTO TraitModifiers 
		(TraitType,						ModifierId) 
VALUES	-- Faith Purchase
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_BUILDINGS_CITYCENTER'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_BUILDINGS_HOLYSITE'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_BUILDINGS_HARBOR'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_BUILDINGS_ENCAMPMENT'),

		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_CIVILIAN'),

		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_RECON'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_SUPPORT'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_MELEE'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_RANGED'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_SIEGE'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_H_CAVAL'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_L_CAVAL'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_R_CAVAL'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_A_CAVAL'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_H_CHARIOT'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_L_CHARIOT'),

		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_NAV_MELEE'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_NAV_RANGED'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_NAV_RAIDER'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_NAV_CARRIER'),

		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_AIRCRAFT'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_FAITH_BUY_UNITS_HELICOPTER');


/*
-- All HS buildings can be purchased with Gold
UPDATE Buildings SET PurchaseYield = "YIELD_GOLD" WHERE PrereqDistrict = "DISTRICT_HOLY_SITE" AND PurchaseYield = "YIELD_FAITH" ;


REPLACE INTO Districts
		(DistrictType,				CanAttack,			ZOC,		HitPoints,		PlunderType,		PlunderAmount,		CityStrengthModifier)	
VALUES
		('DISTRICT_HOLY_SITE',		'1',				'1',		'100',			'NO_PLUNDER',		'0',				'2');

REPLACE INTO Districts_XP2
		(DistrictType,      		 AttackRange)	
VALUES
		('DISTRICT_HOLY_SITE',		'2');
*/