-- MNX_GOTS_GeneralBonus
-- Author: manux
-- DateCreated: 3/2/2024 7:48:37 PM
--------------------------------------------------------------

INSERT INTO Types
			(Type,												Kind)
VALUES		('DMOD_MNX_GOVERNORS_FAITH_PURCHASE_DISTRICTS',		'KIND_MODIFIER'),
			('DMOD_MNX_PCITIES_ADJUST_UNIT_DOMAIN_PRODUCTION',	'KIND_MODIFIER');

-- Districts Faith purchase Effect only seems to work through governors. Can't make it work with cities collection.
INSERT INTO DynamicModifiers
			(ModifierType,										CollectionType,						EffectType)
VALUES		('DMOD_MNX_GOVERNORS_FAITH_PURCHASE_DISTRICTS',		'COLLECTION_PLAYER_GOVERNORS',		'EFFECT_ADJUST_CAN_FAITH_PURCHASE_DISTRICTS'),
			('DMOD_MNX_PCITIES_ADJUST_UNIT_DOMAIN_PRODUCTION',	'COLLECTION_PLAYER_CITIES',			'EFFECT_ADJUST_UNIT_DOMAIN_PRODUCTION');


INSERT OR IGNORE INTO Modifiers 
		(ModifierId,										ModifierType,													Permanent,		SubjectRequirementSetId)
VALUES	-- Grant Technologies
		('MOD_MNX_ASTROLOGY',								'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					1,				NULL),
		('MOD_MNX_SAILING',									'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					1,				NULL),
		('MOD_MNX_CEL_NAV',									'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					1,				NULL),
		('MOD_MNX_SHIPBUILDING',							'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					1,				NULL),

		-- Great People boosts
		('MOD_MNX_PROPHET_POINTS',							'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS',					1,				NULL),
		('MOD_MNX_ADMIRAL_POINTS',							'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS',					1,				NULL),
		('MOD_MNX_MERCHANT_POINTS',							'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS',					1,				NULL),
		('MOD_MNX_GENERAL_POINTS',							'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS',					1,				NULL),
		
		-- City districts limit boost
		('MOD_MNX_DISTRICT_LIMIT_BOOST',					'MODIFIER_PLAYER_CITIES_EXTRA_DISTRICT',						1,				NULL),

		--------------------------------------------------------
		-- Attach Modifiers to Cities
		('MOD_MNX_ATTACH_GOVS_GOLD_PURCHASE_DISTRICTS',		'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',						0,				'REQSR_MNX_CITY_HAS_REL_GOV_HARBOR_TIER2'),

		-- Attached City modifiers
		('MOD_MNX_GOVERNORS_FAITH_PURCHASE_DISTRICTS',		'DMOD_MNX_GOVERNORS_FAITH_PURCHASE_DISTRICTS',					0,				'REQSR_MNX_CITY_HAS_TIER3_HOLY_BUILDING'),
		('MOD_MNX_GOVERNORS_GOLD_PURCHASE_DISTRICTS',		'MODIFIER_CITY_ADJUST_CAN_PURCHASE_DISTRICTS',					0,				NULL),

		-- Units promotions
		('MOD_MNX_APOSTLE_PROMO_DEBATER',					'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION',						1,				'REQSR_MNX_UNIT_IS_RELIGIOUS'),
		('MOD_MNX_RECON_PROMO_RANGER',						'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION',						1,				'REQSR_MNX_UNIT_IS_RECON'),
		('MOD_MNX_RECON_PROMO_ALPINE',						'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION',						1,				'REQSR_MNX_UNIT_IS_RECON'),
		('MOD_MNX_RECON_PROMO_SENTRY',						'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION',						1,				'REQSR_MNX_UNIT_IS_RECON'),
		
		-- Any promotion choice
		('MOD_MNX_APOSTLE_ANY_PROMO',						'MODIFIER_PLAYER_UNIT_GRANT_UNLIMITED_PROMOTION_CHOICES',		1,				NULL),
		('MOD_MNX_ROCKBAND_ANY_PROMO',						'MODIFIER_PLAYER_UNIT_GRANT_UNLIMITED_PROMOTION_CHOICES',		1,				NULL),
		('MOD_MNX_SPY_ANY_PROMO',							'MODIFIER_PLAYER_UNIT_GRANT_UNLIMITED_PROMOTION_CHOICES',		1,				NULL),
		
		-- Policy slots
		('MOD_MNX_POL_SLOT_MILIT_1',						'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		1,				NULL),
		('MOD_MNX_POL_SLOT_DIPLO_1',						'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		1,				NULL),
		('MOD_MNX_POL_SLOT_WILDCARD_1',						'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		1,				'REQSR_MNX_PLAYER_HAS_FOUNDED_RELIGION'),
		('MOD_MNX_POL_SLOT_WILDCARD_2',						'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		1,				NULL),
		
		-- Governor points
		('MOD_MNX_GOV_POINT_1',								'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',						1,				NULL);


INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,										Name,						Value)
VALUES	-- Grant Technologies
		('MOD_MNX_ASTROLOGY',								'TechType',					'TECH_ASTROLOGY'),
		('MOD_MNX_SAILING',									'TechType',					'TECH_SAILING'),
		('MOD_MNX_CEL_NAV',									'TechType',					'TECH_CELESTIAL_NAVIGATION'),
		('MOD_MNX_SHIPBUILDING',							'TechType',					'TECH_SHIPBUILDING'),

		-- Great People boosts
		('MOD_MNX_PROPHET_POINTS',							'GreatPersonClassType',		'GREAT_PERSON_CLASS_PROPHET'),
		('MOD_MNX_PROPHET_POINTS',							'Amount',					'100'),
		('MOD_MNX_ADMIRAL_POINTS',							'GreatPersonClassType',		'GREAT_PERSON_CLASS_ADMIRAL'),
		('MOD_MNX_ADMIRAL_POINTS',							'Amount',					'2'),
		('MOD_MNX_MERCHANT_POINTS',							'GreatPersonClassType',		'GREAT_PERSON_CLASS_MERCHANT'),
		('MOD_MNX_MERCHANT_POINTS',							'Amount',					'2'),
		('MOD_MNX_GENERAL_POINTS',							'GreatPersonClassType',		'GREAT_PERSON_CLASS_GENERAL'),
		('MOD_MNX_GENERAL_POINTS',							'Amount',					'2'),
		
		-- City districts limit boost
		('MOD_MNX_DISTRICT_LIMIT_BOOST',					'Amount',					'10'),

		-- Attach Modifiers to Cities
		('MOD_MNX_ATTACH_GOVS_GOLD_PURCHASE_DISTRICTS',		'ModifierId',				'MOD_MNX_GOVERNORS_GOLD_PURCHASE_DISTRICTS'),
		
		-- Attached City modifiers
		('MOD_MNX_GOVERNORS_FAITH_PURCHASE_DISTRICTS',		'CanPurchase',				'1'),
		('MOD_MNX_GOVERNORS_GOLD_PURCHASE_DISTRICTS',		'CanPurchase',				'1'),

		-- Units promotions
		('MOD_MNX_APOSTLE_PROMO_DEBATER',					'PromotionType',			'PROMOTION_DEBATER'),
		('MOD_MNX_RECON_PROMO_RANGER',						'PromotionType',			'PROMOTION_RANGER'),
		('MOD_MNX_RECON_PROMO_ALPINE',						'PromotionType',			'PROMOTION_ALPINE'),
		('MOD_MNX_RECON_PROMO_SENTRY',						'PromotionType',			'PROMOTION_SENTRY'),

		-- Any promotion choice
		('MOD_MNX_APOSTLE_ANY_PROMO',						'UnitType',					'UNIT_APOSTLE'),
		('MOD_MNX_ROCKBAND_ANY_PROMO',						'UnitType',					'UNIT_ROCK_BAND'),
		('MOD_MNX_SPY_ANY_PROMO',							'UnitType',					'UNIT_SPY'),				
		
		-- Policy slots
		('MOD_MNX_POL_SLOT_MILIT_1',						'GovernmentSlotType',		'SLOT_MILITARY'),
		('MOD_MNX_POL_SLOT_DIPLO_1',						'GovernmentSlotType',		'SLOT_DIPLOMATIC'),
		('MOD_MNX_POL_SLOT_WILDCARD_1',						'GovernmentSlotType',		'SLOT_WILDCARD'),
		('MOD_MNX_POL_SLOT_WILDCARD_2',						'GovernmentSlotType',		'SLOT_WILDCARD'),
		
		-- Governor points
		('MOD_MNX_GOV_POINT_1',								'Delta',					'1');


INSERT OR IGNORE INTO TraitModifiers 
		(TraitType,					ModifierId) 
VALUES	-- Grant Technologies
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_ASTROLOGY'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_SAILING'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_CEL_NAV'),			-- Harbors
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_SHIPBUILDING'),

		-- Great People boosts
		('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_PROPHET_POINTS'),
		('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_ADMIRAL_POINTS'),
		('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_MERCHANT_POINTS'),
		('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_GENERAL_POINTS'),

		-- City districts limit boost
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_DISTRICT_LIMIT_BOOST'),

		-- Purchase Districts with Faith and Gold
		('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_GOVERNORS_FAITH_PURCHASE_DISTRICTS'),
		('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_ATTACH_GOVS_GOLD_PURCHASE_DISTRICTS'),				
		
		-- Units promotions
		--('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_APOSTLE_PROMO_DEBATER'),
		--('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_RECON_PROMO_RANGER'),
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_RECON_PROMO_ALPINE'),
		--('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_RECON_PROMO_SENTRY'),

		-- Any promotion choice
		('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_APOSTLE_ANY_PROMO'),
		--('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_ROCKBAND_ANY_PROMO'),
		--('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_SPY_ANY_PROMO'),
		
		-- Policy slots
		--('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',	'MOD_MNX_POL_SLOT_MILIT_1'),
		--('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',	'MOD_MNX_POL_SLOT_DIPLO_1'),
		('TRAIT_LEADER_MNX_THE_GODS_ARE_WITH_US',	'MOD_MNX_POL_SLOT_WILDCARD_1'),
		--('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',	'MOD_MNX_POL_SLOT_WILDCARD_2'),
		-- Governor points
		('TRAIT_CIVILIZATION_MNX_SONS_OF_ODIN',		'MOD_MNX_GOV_POINT_1');


