-- GodsOfTheSea_Modifiers
-- Author: manux
-- DateCreated: 3/3/2024 6:49:05 PM
--------------------------------------------------------------



/* -- Add modifier to all districts
INSERT OR IGNORE INTO DistrictModifiers
		(DistrictType,			ModifierId)
SELECT	DistrictType,			'MOD_MNX_DIST_FAITH_FROM_ADJ_HOLYSITE' 
FROM Districts;

INSERT OR IGNORE INTO DistrictModifiers
		(DistrictType,			ModifierId)
SELECT	DistrictType,			'MOD_MNX_DIST_GOLD_FROM_ADJ_HARBOR' 
FROM Districts;
*/


INSERT OR IGNORE INTO Modifiers 
		(ModifierId,									ModifierType,													OwnerRequirementSetId)
VALUES 
		
		-- Districts double adjacency
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',					'PLAYER_IS_HUMAN'),
		-- Faith Purchase
		('MOD_MNX_FAITH_BUY_BUILDINGS_CITYCENTER',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',		'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_HOLYSITE',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',		'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_HARBOR',			'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',		'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_CIVILIAN',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),

		('MOD_MNX_FAITH_BUY_UNITS_RECON',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_SUPPORT',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_MELEE',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_RANGED',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_SIEGE',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_H_CAVAL',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_L_CAVAL',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_R_CAVAL',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_A_CAVAL',				'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_H_CHARIOT',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_L_CHARIOT',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),

		('MOD_MNX_FAITH_BUY_UNITS_NAV_MELEE',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_RANGED',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_RAIDER',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_CARRIER',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),

		('MOD_MNX_FAITH_BUY_UNITS_AIRCRAFT',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BUY_UNITS_HELICOPTER',			'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE',			'PLAYER_IS_HUMAN'),
		
		-- Units promotions
		('MOD_MNX_APOSTLE_ANY_PROMO',					'MODIFIER_PLAYER_UNIT_GRANT_UNLIMITED_PROMOTION_CHOICES',		'PLAYER_IS_HUMAN'),
		('MOD_MNX_ROCKBAND_ANY_PROMO',					'MODIFIER_PLAYER_UNIT_GRANT_UNLIMITED_PROMOTION_CHOICES',		'PLAYER_IS_HUMAN'),
		('MOD_MNX_SPY_ANY_PROMO',						'MODIFIER_PLAYER_UNIT_GRANT_UNLIMITED_PROMOTION_CHOICES',		'PLAYER_IS_HUMAN');


INSERT OR IGNORE INTO Modifiers 
		(ModifierId,								ModifierType,															OwnerRequirementSetId,		SubjectRequirementSetId)
VALUES	-- Coastal Housing
		('MOD_MNX_COASTAL_HOUSING',					'MODIFIER_PLAYER_CITIES_ADJUST_WATER_HOUSING',							'PLAYER_IS_HUMAN',		'PLOT_IS_COASTAL_LAND_REQUIREMENTS'),
		-- Units promotions
		('MOD_MNX_APOSTLE_PROMO_DEBATER',			'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION',								'PLAYER_IS_HUMAN',		'REQSR_MNX_UNIT_IS_RELIGIOUS'),
		-- Water adjacent districts gain +1	amenity 
		('MOD_MNX_WATER_DISTRICT_AMENITY',			'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',					'PLAYER_IS_HUMAN',		'REQSR_MNX_WATER_ADJACENCY'),

		-- Districts extra adjacency Yields
		('MOD_MNX_HOLYSITE_ADJ_FOOD',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_PROD',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_1',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_2',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_SCI',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_CULT',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HARBOR_ADJ_FOOD',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'DISTRICT_IS_HARBOR'),
		-- Tiles yields from adjacent Districts
		('MOD_MNX_PLOT_FAITH_FROM_ADJ_HOLYSITE',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',		'REQSR_MNX_PLOT_HAS_ADJ_HOLYSITE'),
		('MOD_MNX_PLOT_GOLD_FROM_ADJ_HARBOR',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',		'REQSR_MNX_PLOT_HAS_ADJ_HARBOR'),
		-- Districts yields from adjacent Holy Site or Harbor
		('MOD_MNX_DIST_FAITH_FROM_ADJ_HOLYSITE',	'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE',					'PLAYER_IS_HUMAN',		'REQSR_MNX_DISTRICT_ADJ_TO_HOLYSITE'),
		('MOD_MNX_DIST_GOLD_FROM_ADJ_HARBOR',		'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE',					'PLAYER_IS_HUMAN',		'REQSR_MNX_DISTRICT_ADJ_TO_HARBOR'),
		-- Holy Site: get yields from other yield producing districts
		('MOD_MNX_HOLYSITE_SCI_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'REQSR_MNX_IS_HOLYSITE_HAS_CAMPUS'),
		('MOD_MNX_HOLYSITE_CULT_FROM_DISTRICTS',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'REQSR_MNX_IS_HOLYSITE_HAS_THEATER'),
		('MOD_MNX_HOLYSITE_GOLD_FROM_DISTRICTS',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'REQSR_MNX_IS_HOLYSITE_HAS_GOLD_DISTRICT'),
		('MOD_MNX_HOLYSITE_PROD_FROM_DISTRICTS',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'REQSR_MNX_IS_HOLYSITE_HAS_INDZONE'),
		-- Harbor: get yields from other yield producing districts
		('MOD_MNX_HARBOR_SCI_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'REQSR_MNX_IS_HARBOR_HAS_CAMPUS'),
		('MOD_MNX_HARBOR_CULT_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'REQSR_MNX_IS_HARBOR_HAS_THEATER'),
		('MOD_MNX_HARBOR_FAITH_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'REQSR_MNX_IS_HARBOR_HAS_HOLYSITE'),
		('MOD_MNX_HARBOR_PROD_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',		'REQSR_MNX_IS_HARBOR_HAS_INDZONE'),
		-- Water yields
		('MOD_MNX_WATER_YIELD_FOOD',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',		'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_PROD',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',		'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_GOLD',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',		'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_FAITH',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',		'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_SCI',					'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',		'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_CULT',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',		'REQSR_MNX_PLOT_HAS_WATER');


INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,						Value)
VALUES	
		-- Districts 2x adjacency
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'DistrictType',				'DISTRICT_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'Amount',					'1'),
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'TilesRequired',			'2'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'DistrictType',				'DISTRICT_HARBOR'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'Amount',					'1'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'TilesRequired',			'2'),
		-- Faith Purchase
		('MOD_MNX_FAITH_BUY_BUILDINGS_CITYCENTER',		'DistrictType',				'DISTRICT_CITY_CENTER'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_HOLYSITE',		'DistrictType',				'DISTRICT_HOLY_SITE'),
		('MOD_MNX_FAITH_BUY_BUILDINGS_HARBOR',			'DistrictType',				'DISTRICT_HARBOR'),
		('MOD_MNX_FAITH_BUY_UNITS_CIVILIAN',			'Tag',						'CLASS_LANDCIVILIAN'),

		('MOD_MNX_FAITH_BUY_UNITS_RECON',				'Tag',						'CLASS_RECON'),
		('MOD_MNX_FAITH_BUY_UNITS_SUPPORT',				'Tag',						'CLASS_SUPPORT'),
		('MOD_MNX_FAITH_BUY_UNITS_MELEE',				'Tag',						'CLASS_MELEE'),
		('MOD_MNX_FAITH_BUY_UNITS_RANGED',				'Tag',						'CLASS_RANGED'),
		('MOD_MNX_FAITH_BUY_UNITS_SIEGE',				'Tag',						'CLASS_SIEGE'),
		('MOD_MNX_FAITH_BUY_UNITS_H_CAVAL',				'Tag',						'CLASS_HEAVY_CAVALRY'),
		('MOD_MNX_FAITH_BUY_UNITS_L_CAVAL',				'Tag',						'CLASS_LIGHT_CAVALRY'),
		('MOD_MNX_FAITH_BUY_UNITS_R_CAVAL',				'Tag',						'CLASS_RANGED_CAVALRY'),
		('MOD_MNX_FAITH_BUY_UNITS_A_CAVAL',				'Tag',						'CLASS_ANTI_CAVALRY'),
		('MOD_MNX_FAITH_BUY_UNITS_H_CHARIOT',			'Tag',						'CLASS_HEAVY_CHARIOT'),
		('MOD_MNX_FAITH_BUY_UNITS_L_CHARIOT',			'Tag',						'CLASS_LIGHT_CHARIOT'),

		('MOD_MNX_FAITH_BUY_UNITS_NAV_MELEE',			'Tag',						'CLASS_NAVAL_MELEE'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_RANGED',			'Tag',						'CLASS_NAVAL_RANGED'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_RAIDER',			'Tag',						'CLASS_NAVAL_RAIDER'),
		('MOD_MNX_FAITH_BUY_UNITS_NAV_CARRIER',			'Tag',						'CLASS_NAVAL_CARRIER'),
		
		('MOD_MNX_FAITH_BUY_UNITS_AIRCRAFT',			'Tag',						'CLASS_AIRCRAFT'),
		('MOD_MNX_FAITH_BUY_UNITS_HELICOPTER',			'Tag',						'CLASS_HELICOPTER'),

		
		-- Units promotions
		('MOD_MNX_APOSTLE_PROMO_DEBATER',				'PromotionType',			'PROMOTION_DEBATER'),
		('MOD_MNX_APOSTLE_ANY_PROMO',					'UnitType',					'UNIT_APOSTLE'),
		('MOD_MNX_ROCKBAND_ANY_PROMO',					'UnitType',					'UNIT_ROCK_BAND'),
		('MOD_MNX_SPY_ANY_PROMO',						'UnitType',					'UNIT_SPY'),
		
		-- Water adjacent districts gain +1 amenity 
		('MOD_MNX_WATER_DISTRICT_AMENITY',				'Amount',					'1'),
		-- Holy Site extra adjacency Yields
		('MOD_MNX_HOLYSITE_ADJ_FOOD',					'YieldTypeToGrant',			'YIELD_FOOD'),
		('MOD_MNX_HOLYSITE_ADJ_FOOD',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_PROD',					'YieldTypeToGrant',			'YIELD_PRODUCTION'),
		('MOD_MNX_HOLYSITE_ADJ_PROD',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_1',					'YieldTypeToGrant',			'YIELD_GOLD'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_1',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_2',					'YieldTypeToGrant',			'YIELD_GOLD'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_2',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_SCI',					'YieldTypeToGrant',			'YIELD_SCIENCE'),
		('MOD_MNX_HOLYSITE_ADJ_SCI',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_CULT',					'YieldTypeToGrant',			'YIELD_CULTURE'),
		('MOD_MNX_HOLYSITE_ADJ_CULT',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HARBOR_ADJ_FOOD',						'YieldTypeToGrant',			'YIELD_FOOD'),
		('MOD_MNX_HARBOR_ADJ_FOOD',						'YieldTypeToMirror',		'YIELD_GOLD'),
		-- Tiles yeilds from adjacent Holy Site or Harbor
		('MOD_MNX_PLOT_FAITH_FROM_ADJ_HOLYSITE',		'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_PLOT_FAITH_FROM_ADJ_HOLYSITE',		'Amount',					'2'),
		('MOD_MNX_PLOT_GOLD_FROM_ADJ_HARBOR',			'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_PLOT_GOLD_FROM_ADJ_HARBOR',			'Amount',					'2'),
		-- Districts yields from adjacent Holy Site or Harbor
		('MOD_MNX_DIST_FAITH_FROM_ADJ_HOLYSITE',		'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_DIST_FAITH_FROM_ADJ_HOLYSITE',		'Amount',					'2'),
		('MOD_MNX_DIST_GOLD_FROM_ADJ_HARBOR',			'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_DIST_GOLD_FROM_ADJ_HARBOR',			'Amount',					'2'),
		-- Holy Site: get yields from other yield producing districts
		('MOD_MNX_HOLYSITE_SCI_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_SCIENCE'),
		('MOD_MNX_HOLYSITE_SCI_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_CULT_FROM_DISTRICTS',		'YieldTypeToGrant',			'YIELD_CULTURE'),
		('MOD_MNX_HOLYSITE_CULT_FROM_DISTRICTS',		'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_GOLD_FROM_DISTRICTS',		'YieldTypeToGrant',			'YIELD_GOLD'),
		('MOD_MNX_HOLYSITE_GOLD_FROM_DISTRICTS',		'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_PROD_FROM_DISTRICTS',		'YieldTypeToGrant',			'YIELD_PRODUCTION'),
		('MOD_MNX_HOLYSITE_PROD_FROM_DISTRICTS',		'YieldTypeToMirror',		'YIELD_FAITH'),
		-- Harbor: get yields from other yield producing districts
		('MOD_MNX_HARBOR_SCI_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_SCIENCE'),
		('MOD_MNX_HARBOR_SCI_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_GOLD'),
		('MOD_MNX_HARBOR_CULT_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_CULTURE'),
		('MOD_MNX_HARBOR_CULT_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_GOLD'),
		('MOD_MNX_HARBOR_FAITH_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_FAITH'),
		('MOD_MNX_HARBOR_FAITH_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_GOLD'),
		('MOD_MNX_HARBOR_PROD_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_PRODUCTION'),
		('MOD_MNX_HARBOR_PROD_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_GOLD'),	
		-- Water yields
		('MOD_MNX_WATER_YIELD_FOOD',					'YieldType',				'YIELD_FOOD'),
		('MOD_MNX_WATER_YIELD_FOOD',					'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_PROD',					'YieldType',				'YIELD_PRODUCTION'),
		('MOD_MNX_WATER_YIELD_PROD',					'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_GOLD',					'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_WATER_YIELD_GOLD',					'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_FAITH',					'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_WATER_YIELD_FAITH',					'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_SCI',						'YieldType',				'YIELD_SCIENCE'),
		('MOD_MNX_WATER_YIELD_SCI',						'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_CULT',					'YieldType',				'YIELD_CULTURE'),
		('MOD_MNX_WATER_YIELD_CULT',					'Amount',					'1'),
		
		-- Coastal Housing
		('MOD_MNX_COASTAL_HOUSING',						'Amount',					'3');


/*
-- All HS buildings can be purchased with Gold
UPDATE Buildings SET PurchaseYield = "YIELD_GOLD" WHERE PrereqDistrict = "DISTRICT_HOLY_SITE" AND PurchaseYield = "YIELD_FAITH" ;


REPLACE INTO Districts
		(DistrictType,				CanAttack,			ZOC,		HitPoints,		PlunderType,		PlunderAmount,		CityStrengthModifier)	
VALUES
		('DISTRICT_HOLY_SITE',		'1',				'1',		'100',			'NO_PLUNDER',		'0',				'2');

REPLACE INTO Districts_XP2
		(DistrictType,      		 AttackRange)	
VALUES
		('DISTRICT_HOLY_SITE',		'2');
*/

INSERT OR IGNORE INTO TraitModifiers 
		(TraitType,					ModifierId) 
VALUES	-- Districts 2x adjacency
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_2X_ADJACENCY'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_2X_ADJACENCY'),
		-- Faith Purchase
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_BUILDINGS_CITYCENTER'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_BUILDINGS_HOLYSITE'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_BUILDINGS_HARBOR'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_CIVILIAN'),

		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_RECON'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_SUPPORT'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_MELEE'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_RANGED'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_SIEGE'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_H_CAVAL'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_L_CAVAL'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_R_CAVAL'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_A_CAVAL'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_H_CHARIOT'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_L_CHARIOT'),

		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_NAV_MELEE'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_NAV_RANGED'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_NAV_RAIDER'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_NAV_CARRIER'),

		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_AIRCRAFT'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FAITH_BUY_UNITS_HELICOPTER'),

		
		-- Units promotions
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_APOSTLE_PROMO_DEBATER'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_APOSTLE_ANY_PROMO'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_ROCKBAND_ANY_PROMO'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_SPY_ANY_PROMO'),
				
		-- Water adjacent districts gain +1 amenity 
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_DISTRICT_AMENITY'),
		-- Holy Site and Harbor extra adjacency Yields
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_FOOD'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_ADJ_FOOD'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_PROD'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_GOLD_1'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_GOLD_2'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_SCI'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_CULT'),

		-- Tiles yeilds from adjacent Districts
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_PLOT_FAITH_FROM_ADJ_HOLYSITE'),	
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_PLOT_GOLD_FROM_ADJ_HARBOR'),
		/*
		-- Holy Site: get yields from other yield producing districts
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_SCI_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_CULT_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_GOLD_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_PROD_FROM_DISTRICTS'),
		-- Harbor: get yields from other yield producing districts
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_SCI_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_CULT_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_FAITH_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_PROD_FROM_DISTRICTS'),
		*/
		-- Water yields
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_FOOD'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_PROD'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_GOLD'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_FAITH'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_SCI'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_CULT'),
		-- Coastal Housing
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_COASTAL_HOUSING');
		
		

		