-- GodsOfTheSea_Modifiers
-- Author: manux
-- DateCreated: 3/3/2024 6:49:05 PM
--------------------------------------------------------------

--INSERT OR IGNORE INTO Types (Type, Kind) VALUES ('TRAIT_REMOVE_REGULAR_DISTRICTS_ADJ', 'KIND_TRAIT');
--INSERT OR IGNORE INTO Traits (TraitType, InternalOnly) VALUES ('TRAIT_REMOVE_REGULAR_DISTRICTS_ADJ', 1);
/*
INSERT OR IGNORE INTO ExcludedAdjacencies 
		(TraitType,						YieldChangeId) 
VALUES	('TRAIT_LEADER_MAJOR_CIV',		'District_Faith'),
		('TRAIT_LEADER_MAJOR_CIV',		'District_Science'),
		('TRAIT_LEADER_MAJOR_CIV',		'District_Gold'),
		('TRAIT_LEADER_MAJOR_CIV',		'District_Culture'),
		('TRAIT_LEADER_MAJOR_CIV',		'District_Production');
*/

INSERT OR IGNORE INTO Modifiers 
		(ModifierId,								ModifierType,															OwnerRequirementSetId,		SubjectRequirementSetId)
VALUES	-- Districts double adjacency
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',			'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',							'PLAYER_IS_HUMAN',			'REQSR_MNX_CIV_NOT_JAPAN'),
		('MOD_MNX_HOLYSITE_REM_REG_ADJACENCY',		'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',							'PLAYER_IS_HUMAN',			'REQSR_MNX_CIV_NOT_JAPAN'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',				'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',							'PLAYER_IS_HUMAN',			'REQSR_MNX_CIV_NOT_JAPAN'),
		('MOD_MNX_HARBOR_REM_REG_ADJACENCY',		'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',							'PLAYER_IS_HUMAN',			'REQSR_MNX_CIV_NOT_JAPAN'),
		-- Coastal Housing
		('MOD_MNX_COASTAL_HOUSING',					'MODIFIER_PLAYER_CITIES_ADJUST_WATER_HOUSING',							'PLAYER_IS_HUMAN',			'PLOT_IS_COASTAL_LAND_REQUIREMENTS'),
		-- Water adjacent districts gain +1	amenity 
		('MOD_MNX_WATER_DISTRICT_AMENITY',			'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_ENTERTAINMENT',					'PLAYER_IS_HUMAN',			'REQSR_MNX_WATER_ADJACENCY'),
		-- Districts extra adjacency Yields
		('MOD_MNX_HOLYSITE_ADJ_FOOD',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_PROD',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_1',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_2',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_SCI',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_ADJ_CULT',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'DISTRICT_IS_HOLY_SITE'),
		('MOD_MNX_HARBOR_ADJ_FOOD',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'DISTRICT_IS_HARBOR'),
		-- Tiles yields from adjacent Districts
		('MOD_MNX_PLOT_FAITH_FROM_ADJ_HOLYSITE',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',			'REQSR_MNX_PLOT_HAS_ADJ_HOLYSITE'),
		('MOD_MNX_PLOT_GOLD_FROM_ADJ_HARBOR',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',			'REQSR_MNX_PLOT_HAS_ADJ_HARBOR'),
		-- Districts yields from adjacent Holy Site or Harbor
		('MOD_MNX_DIST_FAITH_FROM_ADJ_HOLYSITE',	'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE',					'PLAYER_IS_HUMAN',			'REQSR_MNX_DISTRICT_ADJ_TO_HOLYSITE'),
		('MOD_MNX_DIST_GOLD_FROM_ADJ_HARBOR',		'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE',					'PLAYER_IS_HUMAN',			'REQSR_MNX_DISTRICT_ADJ_TO_HARBOR'),
		-- Holy Site: get yields from other yield producing districts
		('MOD_MNX_HOLYSITE_SCI_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'REQSR_MNX_IS_HOLYSITE_HAS_CAMPUS'),
		('MOD_MNX_HOLYSITE_CULT_FROM_DISTRICTS',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'REQSR_MNX_IS_HOLYSITE_HAS_THEATER'),
		('MOD_MNX_HOLYSITE_GOLD_FROM_DISTRICTS',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'REQSR_MNX_IS_HOLYSITE_HAS_GOLD_DISTRICT'),
		('MOD_MNX_HOLYSITE_PROD_FROM_DISTRICTS',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'REQSR_MNX_IS_HOLYSITE_HAS_INDZONE'),
		-- Harbor: get yields from other yield producing districts
		('MOD_MNX_HARBOR_SCI_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'REQSR_MNX_IS_HARBOR_HAS_CAMPUS'),
		('MOD_MNX_HARBOR_CULT_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'REQSR_MNX_IS_HARBOR_HAS_THEATER'),
		('MOD_MNX_HARBOR_FAITH_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'REQSR_MNX_IS_HARBOR_HAS_HOLYSITE'),
		('MOD_MNX_HARBOR_PROD_FROM_DISTRICTS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'PLAYER_IS_HUMAN',			'REQSR_MNX_IS_HARBOR_HAS_INDZONE'),
		-- Water yields
		('MOD_MNX_WATER_YIELD_FOOD',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',			'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_PROD',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',			'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_GOLD',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',			'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_FAITH',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',			'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_SCI',					'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',			'REQSR_MNX_PLOT_HAS_WATER'),
		('MOD_MNX_WATER_YIELD_CULT',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',									'PLAYER_IS_HUMAN',			'REQSR_MNX_PLOT_HAS_WATER');


INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,						Value)
VALUES	-- Districts 2x adjacency
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'DistrictType',				'DISTRICT_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'Amount',					'1'),
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'TilesRequired',			'1'),
		('MOD_MNX_HOLYSITE_2X_ADJACENCY',				'OtherDistrictAdjacent',	'1'),

		('MOD_MNX_HOLYSITE_REM_REG_ADJACENCY',			'DistrictType',				'DISTRICT_HOLY_SITE'),
		('MOD_MNX_HOLYSITE_REM_REG_ADJACENCY',			'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_REM_REG_ADJACENCY',			'Amount',					'-1'),
		('MOD_MNX_HOLYSITE_REM_REG_ADJACENCY',			'TilesRequired',			'2'),
		('MOD_MNX_HOLYSITE_REM_REG_ADJACENCY',			'OtherDistrictAdjacent',	'1'),
		
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'DistrictType',				'DISTRICT_HARBOR'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'Amount',					'1'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'TilesRequired',			'1'),
		('MOD_MNX_HARBOR_2X_ADJACENCY',					'OtherDistrictAdjacent',	'1'),

		('MOD_MNX_HARBOR_REM_REG_ADJACENCY',			'DistrictType',				'DISTRICT_HARBOR'),
		('MOD_MNX_HARBOR_REM_REG_ADJACENCY',			'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_HARBOR_REM_REG_ADJACENCY',			'Amount',					'-1'),
		('MOD_MNX_HARBOR_REM_REG_ADJACENCY',			'TilesRequired',			'2'),
		('MOD_MNX_HARBOR_REM_REG_ADJACENCY',			'OtherDistrictAdjacent',	'1'),
			
		-- Water adjacent districts gain +1 amenity 
		('MOD_MNX_WATER_DISTRICT_AMENITY',				'Amount',					'1'),
		-- Holy Site extra adjacency Yields
		('MOD_MNX_HOLYSITE_ADJ_FOOD',					'YieldTypeToGrant',			'YIELD_FOOD'),
		('MOD_MNX_HOLYSITE_ADJ_FOOD',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_PROD',					'YieldTypeToGrant',			'YIELD_PRODUCTION'),
		('MOD_MNX_HOLYSITE_ADJ_PROD',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_1',					'YieldTypeToGrant',			'YIELD_GOLD'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_1',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_2',					'YieldTypeToGrant',			'YIELD_GOLD'),
		('MOD_MNX_HOLYSITE_ADJ_GOLD_2',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_SCI',					'YieldTypeToGrant',			'YIELD_SCIENCE'),
		('MOD_MNX_HOLYSITE_ADJ_SCI',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_ADJ_CULT',					'YieldTypeToGrant',			'YIELD_CULTURE'),
		('MOD_MNX_HOLYSITE_ADJ_CULT',					'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HARBOR_ADJ_FOOD',						'YieldTypeToGrant',			'YIELD_FOOD'),
		('MOD_MNX_HARBOR_ADJ_FOOD',						'YieldTypeToMirror',		'YIELD_GOLD'),
		-- Tiles yeilds from adjacent Holy Site or Harbor
		('MOD_MNX_PLOT_FAITH_FROM_ADJ_HOLYSITE',		'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_PLOT_FAITH_FROM_ADJ_HOLYSITE',		'Amount',					'2'),
		('MOD_MNX_PLOT_GOLD_FROM_ADJ_HARBOR',			'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_PLOT_GOLD_FROM_ADJ_HARBOR',			'Amount',					'2'),
		-- Districts yields from adjacent Holy Site or Harbor
		('MOD_MNX_DIST_FAITH_FROM_ADJ_HOLYSITE',		'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_DIST_FAITH_FROM_ADJ_HOLYSITE',		'Amount',					'2'),
		('MOD_MNX_DIST_GOLD_FROM_ADJ_HARBOR',			'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_DIST_GOLD_FROM_ADJ_HARBOR',			'Amount',					'2'),
		-- Holy Site: get yields from other yield producing districts
		('MOD_MNX_HOLYSITE_SCI_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_SCIENCE'),
		('MOD_MNX_HOLYSITE_SCI_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_CULT_FROM_DISTRICTS',		'YieldTypeToGrant',			'YIELD_CULTURE'),
		('MOD_MNX_HOLYSITE_CULT_FROM_DISTRICTS',		'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_GOLD_FROM_DISTRICTS',		'YieldTypeToGrant',			'YIELD_GOLD'),
		('MOD_MNX_HOLYSITE_GOLD_FROM_DISTRICTS',		'YieldTypeToMirror',		'YIELD_FAITH'),
		('MOD_MNX_HOLYSITE_PROD_FROM_DISTRICTS',		'YieldTypeToGrant',			'YIELD_PRODUCTION'),
		('MOD_MNX_HOLYSITE_PROD_FROM_DISTRICTS',		'YieldTypeToMirror',		'YIELD_FAITH'),
		-- Harbor: get yields from other yield producing districts
		('MOD_MNX_HARBOR_SCI_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_SCIENCE'),
		('MOD_MNX_HARBOR_SCI_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_GOLD'),
		('MOD_MNX_HARBOR_CULT_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_CULTURE'),
		('MOD_MNX_HARBOR_CULT_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_GOLD'),
		('MOD_MNX_HARBOR_FAITH_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_FAITH'),
		('MOD_MNX_HARBOR_FAITH_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_GOLD'),
		('MOD_MNX_HARBOR_PROD_FROM_DISTRICTS',			'YieldTypeToGrant',			'YIELD_PRODUCTION'),
		('MOD_MNX_HARBOR_PROD_FROM_DISTRICTS',			'YieldTypeToMirror',		'YIELD_GOLD'),	
		-- Water yields
		('MOD_MNX_WATER_YIELD_FOOD',					'YieldType',				'YIELD_FOOD'),
		('MOD_MNX_WATER_YIELD_FOOD',					'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_PROD',					'YieldType',				'YIELD_PRODUCTION'),
		('MOD_MNX_WATER_YIELD_PROD',					'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_GOLD',					'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_WATER_YIELD_GOLD',					'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_FAITH',					'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_WATER_YIELD_FAITH',					'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_SCI',						'YieldType',				'YIELD_SCIENCE'),
		('MOD_MNX_WATER_YIELD_SCI',						'Amount',					'1'),
		('MOD_MNX_WATER_YIELD_CULT',					'YieldType',				'YIELD_CULTURE'),
		('MOD_MNX_WATER_YIELD_CULT',					'Amount',					'1'),
		
		-- Coastal Housing
		('MOD_MNX_COASTAL_HOUSING',						'Amount',					'3');


 -- Add modifiers to all districts to get Yields from Holy Site and Harbor
INSERT OR IGNORE INTO DistrictModifiers
		(DistrictType,			ModifierId)
SELECT	DistrictType,			'MOD_MNX_DIST_FAITH_FROM_ADJ_HOLYSITE' 
FROM Districts;

INSERT OR IGNORE INTO DistrictModifiers
		(DistrictType,			ModifierId)
SELECT	DistrictType,			'MOD_MNX_DIST_GOLD_FROM_ADJ_HARBOR' 
FROM Districts;


INSERT OR IGNORE INTO TraitModifiers 
		(TraitType,					ModifierId) 
VALUES	-- Districts 2x adjacency
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_2X_ADJACENCY'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_2X_ADJACENCY'),	
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_REM_REG_ADJACENCY'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_REM_REG_ADJACENCY'),		
		-- Water adjacent districts gain +1 amenity 
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_DISTRICT_AMENITY'),
		-- Holy Site and Harbor extra adjacency Yields
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_FOOD'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_ADJ_FOOD'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_PROD'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_GOLD_1'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_GOLD_2'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_SCI'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_ADJ_CULT'),
		-------------------------------------------------------------------
		-- Tiles yeilds from adjacent Districts
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_PLOT_FAITH_FROM_ADJ_HOLYSITE'),	
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_PLOT_GOLD_FROM_ADJ_HARBOR'),
		-- Holy Site: get yields from other yield producing districts
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_SCI_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_CULT_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_GOLD_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HOLYSITE_PROD_FROM_DISTRICTS'),
		-- Harbor: get yields from other yield producing districts
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_SCI_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_CULT_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_FAITH_FROM_DISTRICTS'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_HARBOR_PROD_FROM_DISTRICTS'),
		-- Water yields
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_FOOD'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_PROD'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_GOLD'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_FAITH'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_SCI'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_WATER_YIELD_CULT'),
		-- Coastal Housing
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_COASTAL_HOUSING');
		
		

		