-- OP_Player
-- Author: manux
-- DateCreated: 3/2/2024 7:48:37 PM
--------------------------------------------------------------

INSERT OR IGNORE INTO Modifiers 
		(ModifierId,									ModifierType,													OwnerRequirementSetId)
VALUES	-- Unlock Techs
		('MOD_MNX_SAILING',								'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_SHIPBUILDING',						'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_CEL_NAV',								'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_CARTOGRAPHY',							'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_FLIGHT',								'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_ADV_FLIGHT',							'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_SYNTH_MAT',							'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_COMB_ARMS',							'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY',					'PLAYER_IS_HUMAN'),
		-- Great People boosts
		('MOD_MNX_PROPHET_POINTS',						'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_ADMIRAL_POINTS',						'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS',					'PLAYER_IS_HUMAN'),
		('MOD_MNX_MERCHANT_POINTS',						'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS',					'PLAYER_IS_HUMAN'),
		-- Cities Yields boosts
		('MOD_MNX_GOLD_BOOST',							'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',				'PLAYER_IS_HUMAN'),
		('MOD_MNX_PROD_BOOST',							'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',				'PLAYER_IS_HUMAN'),
		('MOD_MNX_SCI_BOOST',							'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',				'PLAYER_IS_HUMAN'),
		('MOD_MNX_CULT_BOOST',							'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',				'PLAYER_IS_HUMAN'),
		('MOD_MNX_FAITH_BOOST',							'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',				'PLAYER_IS_HUMAN'),
		('MOD_MNX_FOOD_BOOST',							'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',				'PLAYER_IS_HUMAN'),
		-- Unit boosts
		('MOD_MNX_UNIT_MOVEMENT_BOOST',					'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT',						'PLAYER_IS_HUMAN'),
		('MOD_MNX_UNIT_STRENGTH_BOOST',					'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH',					'PLAYER_IS_HUMAN'),
		-- Water unlock
		('MOD_MNX_EMBARK',								'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',							'PLAYER_IS_HUMAN'),
		('MOD_MNX_OCEAN',								'MODIFIER_PLAYER_UNITS_ADJUST_VALID_TERRAIN',					'PLAYER_IS_HUMAN'),
		-- City districts limit boost
		('MOD_MNX_DISTRICT_LIMIT_BOOST',				'MODIFIER_PLAYER_CITIES_EXTRA_DISTRICT',						'PLAYER_IS_HUMAN'),
		-- Governor points
		('MOD_MNX_GOV_POINT_1',							'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',						'PLAYER_IS_HUMAN'),
		-- Policy slots
		('MOD_MNX_POL_SLOT_MILIT_1',					'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		'PLAYER_IS_HUMAN'),
		('MOD_MNX_POL_SLOT_DIPLO_1',					'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		'PLAYER_IS_HUMAN'),
		('MOD_MNX_POL_SLOT_WILDCARD_1',					'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		'PLAYER_IS_HUMAN'),
		('MOD_MNX_POL_SLOT_WILDCARD_2',					'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		'PLAYER_IS_HUMAN');


INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,						Value)
VALUES	-- Unlock Techs
		('MOD_MNX_SAILING',								'TechType',					'TECH_SAILING'),
		('MOD_MNX_SHIPBUILDING',						'TechType',					'TECH_SHIPBUILDING'),
		('MOD_MNX_CEL_NAV',								'TechType',					'TECH_CELESTIAL_NAVIGATION'),
		('MOD_MNX_CARTOGRAPHY',							'TechType',					'TECH_CARTOGRAPHY'),
		('MOD_MNX_FLIGHT',								'TechType',					'TECH_FLIGHT'),
		('MOD_MNX_ADV_FLIGHT',							'TechType',					'TECH_ADVANCED_FLIGHT'),
		('MOD_MNX_SYNTH_MAT',							'TechType',					'TECH_SYNTHETIC_MATERIALS'),
		('MOD_MNX_COMB_ARMS',							'TechType',					'TECH_COMBINED_ARMS'),
		-- Great People boosts
		('MOD_MNX_PROPHET_POINTS',						'GreatPersonClassType',		'GREAT_PERSON_CLASS_PROPHET'),
		('MOD_MNX_PROPHET_POINTS',						'Amount',					'10'),
		('MOD_MNX_ADMIRAL_POINTS',						'GreatPersonClassType',		'GREAT_PERSON_CLASS_ADMIRAL'),
		('MOD_MNX_ADMIRAL_POINTS',						'Amount',					'10'),
		('MOD_MNX_MERCHANT_POINTS',						'GreatPersonClassType',		'GREAT_PERSON_CLASS_MERCHANT'),
		('MOD_MNX_MERCHANT_POINTS',						'Amount',					'10'),
		-- Cities Yields boosts
		('MOD_MNX_GOLD_BOOST',							'YieldType',				'YIELD_GOLD'),
		('MOD_MNX_GOLD_BOOST',							'Amount',					'1000'),
		('MOD_MNX_FAITH_BOOST',							'YieldType',				'YIELD_FAITH'),
		('MOD_MNX_FAITH_BOOST',							'Amount',					'1000'),
		('MOD_MNX_FOOD_BOOST',							'YieldType',				'YIELD_FOOD'),
		('MOD_MNX_FOOD_BOOST',							'Amount',					'50'),
		('MOD_MNX_PROD_BOOST',							'YieldType',				'YIELD_PRODUCTION'),
		('MOD_MNX_PROD_BOOST',							'Amount',					'100'),
		('MOD_MNX_SCI_BOOST',							'YieldType',				'YIELD_SCIENCE'),
		('MOD_MNX_SCI_BOOST',							'Amount',					'100'),
		('MOD_MNX_CULT_BOOST',							'YieldType',				'YIELD_CULTURE'),
		('MOD_MNX_CULT_BOOST',							'Amount',					'100'),
		-- Unit boosts
		('MOD_MNX_UNIT_MOVEMENT_BOOST',					'Amount',					'5'),
		('MOD_MNX_UNIT_STRENGTH_BOOST',					'Amount',					'50'),
		-- Water unlock
		('MOD_MNX_EMBARK',								'AbilityType',				'ABILITY_MANA'),
		('MOD_MNX_OCEAN',								'TerrainType',				'TERRAIN_OCEAN'),
		('MOD_MNX_OCEAN',								'Valid',					'1'),
		-- City districts limit boost
		('MOD_MNX_DISTRICT_LIMIT_BOOST',				'Amount',					'5'),
		-- Governor points
		('MOD_MNX_GOV_POINT_1',							'Delta',					'10'),
		-- Policy slots
		('MOD_MNX_POL_SLOT_MILIT_1',					'GovernmentSlotType',		'SLOT_MILITARY'),
		('MOD_MNX_POL_SLOT_DIPLO_1',					'GovernmentSlotType',		'SLOT_DIPLOMATIC'),
		('MOD_MNX_POL_SLOT_WILDCARD_1',					'GovernmentSlotType',		'SLOT_WILDCARD'),
		('MOD_MNX_POL_SLOT_WILDCARD_2',					'GovernmentSlotType',		'SLOT_WILDCARD');


INSERT OR IGNORE INTO TraitModifiers 
		(TraitType,					ModifierId) 
VALUES	-- Unlock Techs
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_SAILING'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_SHIPBUILDING'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_CEL_NAV'),
		('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_CARTOGRAPHY'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_FLIGHT'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_ADV_FLIGHT'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_SYNTH_MAT'),
		--('TRAIT_LEADER_MAJOR_CIV', 'MOD_MNX_COMB_ARMS'),

		-- Great People boosts
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_PROPHET_POINTS'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_ADMIRAL_POINTS'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_MERCHANT_POINTS'),		
		-- Cities Yields boosts
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_GOLD_BOOST'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_PROD_BOOST'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_SCI_BOOST'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_CULT_BOOST'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_FAITH_BOOST'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_FOOD_BOOST'),
		-- Unique Units
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_UNIQUE_UNIT_DROMON'),
		-- Unit boosts
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_UNIT_MOVEMENT_BOOST'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_UNIT_STRENGTH_BOOST'),
		-- Units Abilities
		--('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_EMBARK'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_OCEAN'),

		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_IGNORE_EMBARK_DISEMBARK_COST'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_FIGHT_WHILE_EMBARKED'),		
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_SHIP_HEAL_NEUTRAL'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_WATER_TRADER_PROTECT'),
		
		-- City districts limit boost
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_DISTRICT_LIMIT_BOOST'),
		-- Policy slots
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_POL_SLOT_MILIT_1'),
		--('TRAIT_LEADER_MAJOR_CIV',	'MOD_MNX_POL_SLOT_DIPLO_1'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_POL_SLOT_WILDCARD_1'),
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_POL_SLOT_WILDCARD_2'),
		-- Governor points
		('TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_GOV_POINT_1');


INSERT OR IGNORE INTO Modifiers
		(ModifierId,					ModifierType,											RunOnce,	Permanent)
SELECT	'MOD_MNX_EMBARK'||UnitType,		'MODIFIER_PLAYER_ADJUST_EMBARK_UNIT_PASS',				0,			1
FROM	Units	
WHERE Domain='DOMAIN_LAND';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,							Value)
SELECT	'MOD_MNX_EMBARK'||UnitType,						'UnitType',						UnitType
FROM	Units	WHERE Domain='DOMAIN_LAND';

INSERT OR IGNORE INTO TraitModifiers
		(TraitType,						ModifierId)
SELECT	'TRAIT_LEADER_MAJOR_CIV',		'MOD_MNX_EMBARK'||UnitType
FROM	Units	
WHERE Domain='DOMAIN_LAND';